const String inventoryMobilePageHtml = r'''<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#386641">
  <title>JamooManager 在庫・販売</title>
  <style>
    :root{color-scheme:light;--green:#386641;--green2:#6a994e;--pale:#f3f8ef;--card:#fff;--line:#d8e2d2;--red:#b3261e;--redbg:#ffdad6;--text:#1f2a1f;--muted:#647064}
    *{box-sizing:border-box}body{margin:0;background:var(--pale);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans JP",sans-serif}
    button,input,select,textarea{font:inherit}button{cursor:pointer}.hidden{display:none!important}
    header{position:sticky;top:0;z-index:5;background:#edf5e8eF;backdrop-filter:blur(10px);border-bottom:1px solid var(--line);padding:12px 14px}
    .head{max-width:900px;margin:auto;display:flex;align-items:center;gap:10px}.title{font-weight:800;font-size:19px;flex:1}.facility{font-size:12px;color:var(--muted)}
    main{max-width:900px;margin:auto;padding:14px 14px 90px}.search{display:flex;gap:8px;margin-bottom:12px}.search input{flex:1}.scan-btn{min-width:94px}
    input,select,textarea{width:100%;border:1px solid #849181;background:white;border-radius:11px;padding:12px;color:var(--text)}
    .btn{border:0;border-radius:999px;padding:10px 15px;background:var(--green);color:white;font-weight:700;white-space:nowrap}.btn.light{background:#dcefd7;color:#24512e}.btn.outline{background:white;color:var(--green);border:1px solid var(--green)}.btn.danger{background:var(--redbg);color:var(--red)}
    .summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:14px}.sum{background:#e2e8df;border-radius:14px;padding:12px}.sum small{display:block;color:var(--muted)}.sum strong{font-size:21px}
    .items{display:grid;gap:10px}.item{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:14px;box-shadow:0 1px 2px #0000000b}.item.low{border-color:#e7a7a1}
    .item-top{display:flex;gap:10px;align-items:flex-start}.item-name{font-size:17px;font-weight:800;flex:1}.category{font-size:12px;color:var(--muted);margin-top:2px}.stock{text-align:right}.stock strong{display:block;font-size:22px}.low .stock strong{color:var(--red)}
    .prices{display:flex;gap:16px;color:var(--muted);font-size:13px;margin:10px 0}.actions{display:flex;gap:7px;flex-wrap:wrap}.actions .btn{flex:1;min-width:90px;padding:9px 10px}
    .empty{text-align:center;background:white;border:1px solid var(--line);padding:32px;border-radius:16px;color:var(--muted)}
    .overlay{position:fixed;inset:0;z-index:20;background:#17201799;display:flex;align-items:flex-end;justify-content:center}.panel{width:100%;max-width:600px;max-height:92vh;overflow:auto;background:var(--pale);border-radius:22px 22px 0 0;padding:20px}.panel h2{margin:0 0 14px}.field{margin:12px 0}.field label{display:block;font-size:13px;font-weight:700;margin:0 0 5px}.panel-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:18px}.panel-actions .btn{min-width:110px}
    .login{align-items:center}.login .panel{border-radius:22px;max-width:420px}.code{font-size:24px;letter-spacing:5px;text-align:center;font-weight:800}.help{font-size:13px;color:var(--muted);line-height:1.6}
    .toast{position:fixed;left:50%;bottom:22px;z-index:40;transform:translateX(-50%);background:#243124;color:white;padding:11px 18px;border-radius:999px;box-shadow:0 4px 18px #0003;max-width:90%;text-align:center}
    .error{background:var(--redbg);color:var(--red);border-radius:11px;padding:10px;margin:10px 0}.spinner{padding:35px;text-align:center;color:var(--muted)}
    .scan-video{width:100%;max-height:45vh;background:#111;border-radius:14px;object-fit:cover}.scan-box{border:1px dashed var(--green);border-radius:14px;padding:12px;margin:12px 0}.scan-row{display:flex;gap:8px}.scan-row input{flex:1}.file-label{display:block;text-align:center;margin:10px 0}.scan-status{min-height:24px;font-weight:700;color:var(--green)}
    @media(max-width:560px){.summary{grid-template-columns:repeat(2,1fr)}.sum:last-child{grid-column:span 2}.prices{gap:10px}.actions .btn{min-width:72px}.facility{display:none}}
  </style>
</head>
<body>
  <header><div class="head"><div><div class="title">在庫・販売</div><div id="facility" class="facility">JamooManager</div></div><button id="reload" class="btn light">更新</button><button id="logout" class="btn outline">コード再入力</button></div></header>
  <main>
    <div class="search"><input id="search" inputmode="search" placeholder="商品名・コード・バーコードで検索"><button id="scan" class="btn scan-btn">読み取り</button><button id="clear" class="btn light">クリア</button></div>
    <div class="summary"><div class="sum"><small>登録商品</small><strong id="itemCount">0件</strong></div><div class="sum"><small>在庫不足</small><strong id="lowCount">0件</strong></div><div class="sum"><small>表示中</small><strong id="shownCount">0件</strong></div></div>
    <div id="content" class="spinner">接続しています…</div>
  </main>

  <div id="login" class="overlay login hidden"><div class="panel"><h2>接続コード</h2><p class="help">Windows版JamooManagerの「端末接続」に表示された8桁のコードを入力してください。</p><input id="token" class="code" inputmode="numeric" maxlength="8" autocomplete="one-time-code" placeholder="00000000"><div id="loginError" class="error hidden"></div><div class="panel-actions"><button id="connect" class="btn">接続</button></div></div></div>

  <div id="movement" class="overlay hidden"><div class="panel"><h2 id="movementTitle">入出庫・販売</h2><div id="movementStock" class="help"></div><div class="field"><label for="type">処理</label><select id="type"><option value="sale">販売</option><option value="purchase">入荷</option><option value="internal_use">館内使用</option><option value="waste">廃棄</option><option value="return_to_stock">返品・在庫戻し</option><option value="adjustment">棚卸調整</option></select></div><div class="field"><label id="quantityLabel" for="quantity">数量</label><input id="quantity" inputmode="decimal" value="1"></div><div class="field"><label for="price">単価（円・任意）</label><input id="price" inputmode="numeric"></div><div class="field"><label for="note">備考（任意）</label><textarea id="note" rows="2"></textarea></div><div id="movementError" class="error hidden"></div><div class="panel-actions"><button id="cancelMovement" class="btn outline">キャンセル</button><button id="saveMovement" class="btn">記録</button></div></div></div>

  <div id="scanner" class="overlay hidden"><div class="panel"><h2>バーコード読み取り</h2><p class="help">商品のJAN・EAN・UPC・Code・QRを読み取ります。USBリーダーは下の欄にカーソルを置いて読み取ってください。</p><video id="scanVideo" class="scan-video hidden" playsinline muted></video><div id="scanStatus" class="scan-status"></div><label class="btn light file-label" for="scanPhoto">カメラで撮影・写真を選択</label><input id="scanPhoto" class="hidden" type="file" accept="image/*" capture="environment"><div class="scan-box"><label for="scanCode">番号入力・USBバーコードリーダー</label><div class="scan-row"><input id="scanCode" inputmode="numeric" autocomplete="off" placeholder="バーコード番号"><button id="useScanCode" class="btn">検索</button></div></div><div id="scanError" class="error hidden"></div><div class="panel-actions"><button id="cancelScan" class="btn outline">閉じる</button></div></div></div>

  <div id="assignBarcode" class="overlay hidden"><div class="panel"><h2>未登録のバーコード</h2><p id="unknownBarcode" class="help"></p><div class="field"><label for="assignItem">紐付ける既存商品</label><select id="assignItem"></select></div><div id="assignError" class="error hidden"></div><div class="panel-actions"><button id="cancelAssign" class="btn outline">キャンセル</button><button id="newFromBarcode" class="btn light">新しい商品として登録</button><button id="saveAssign" class="btn">既存商品に紐付け</button></div></div></div>

  <div id="newItem" class="overlay hidden"><div class="panel"><h2>バーコードから商品登録</h2><p id="newItemBarcode" class="help"></p><div class="field"><label for="newName">商品名 *</label><input id="newName" autocomplete="off"></div><div class="field"><label for="newCategory">分類 *</label><input id="newCategory" value="食品" autocomplete="off"></div><div class="field"><label for="newUnit">単位 *</label><input id="newUnit" value="個" autocomplete="off"></div><div class="field"><label for="newStock">初期在庫</label><input id="newStock" inputmode="decimal" value="0"></div><div class="field"><label for="newReorder">最低在庫</label><input id="newReorder" inputmode="decimal" value="0"></div><div class="field"><label for="newCost">仕入単価（円・任意）</label><input id="newCost" inputmode="numeric"></div><div class="field"><label for="newSale">販売価格（円・任意）</label><input id="newSale" inputmode="numeric"></div><div class="field"><label for="newSupplier">仕入先（任意）</label><input id="newSupplier" autocomplete="off"></div><div id="newItemError" class="error hidden"></div><div class="panel-actions"><button id="cancelNewItem" class="btn outline">キャンセル</button><button id="saveNewItem" class="btn">商品を登録</button></div></div></div>

  <div id="toast" class="toast hidden"></div>
  <script>
    const state={token:localStorage.getItem('jamoo_inventory_token')||'',items:[],selected:null,loading:false};
    const el=id=>document.getElementById(id);
    const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const qty=value=>Number.isInteger(Number(value))?String(Number(value)):Number(value).toFixed(3).replace(/\.?0+$/,'');
    const yen=value=>value==null?'－':'¥'+Number(value).toLocaleString('ja-JP');
    const uuid=()=>globalThis.crypto?.randomUUID?.()||'mobile-'+Date.now()+'-'+Math.random().toString(16).slice(2);
    function normalizeNumber(value){return String(value??'').trim().replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xFEE0)).replace(/．/g,'.').replace(/－/g,'-').replace(/[，,\s¥￥円]/g,'')}
    function readNumber(value,{empty=null}={}){const text=normalizeNumber(value);if(text==='')return empty;const number=Number(text);return Number.isFinite(number)?number:NaN}

    async function api(path,options={}){
      const headers={'X-Jamoo-Token':state.token,...(options.headers||{})};
      if(options.body)headers['Content-Type']='application/json';
      const response=await fetch(path,{...options,headers});
      let data={};try{data=await response.json()}catch(_){data={error:'応答を読み込めませんでした。'}}
      if(response.status===401){showLogin('接続コードを確認してください。');throw new Error(data.error||'認証できませんでした。')}
      if(!response.ok)throw new Error(data.error||'処理に失敗しました。');return data;
    }
    function showLogin(message=''){el('loginError').textContent=message;el('loginError').classList.toggle('hidden',!message);el('login').classList.remove('hidden');setTimeout(()=>el('token').focus(),50)}
    function hideLogin(){el('login').classList.add('hidden');el('loginError').classList.add('hidden')}
    function toast(message){el('toast').textContent=message;el('toast').classList.remove('hidden');setTimeout(()=>el('toast').classList.add('hidden'),2400)}
    async function connect(){const token=el('token').value.trim();if(!/^\d{8}$/.test(token)){showLogin('8桁の数字を入力してください。');return}state.token=token;try{const health=await api('/api/v1/health');localStorage.setItem('jamoo_inventory_token',token);el('facility').textContent=health.facilityName||'JamooManager';hideLogin();await loadItems()}catch(error){showLogin(error.message)}}
    async function loadItems(silent=false){if(state.loading||!state.token)return;state.loading=true;if(!silent){el('content').className='spinner';el('content').textContent='読み込み中…'}try{const health=await api('/api/v1/health');el('facility').textContent=health.facilityName||'JamooManager';const data=await api('/api/v1/inventory/items');state.items=data.items||[];render()}catch(error){if(!state.token)return;if(!silent||!state.items.length){el('content').className='error';el('content').textContent='接続が切れています。Windows版で「端末接続」を開き、この画面を更新してください。'}}finally{state.loading=false}}
    function render(){const term=el('search').value.trim().toLowerCase();const items=state.items.filter(item=>[item.name,item.category,item.sku,item.barcode].some(value=>String(value||'').toLowerCase().includes(term)));el('itemCount').textContent=state.items.length+'件';el('lowCount').textContent=state.items.filter(item=>Number(item.currentStock)<=Number(item.reorderLevel)).length+'件';el('shownCount').textContent=items.length+'件';if(!items.length){el('content').className='empty';el('content').textContent='該当する商品がありません。';return}el('content').className='items';el('content').innerHTML=items.map(item=>{const low=Number(item.currentStock)<=Number(item.reorderLevel);return `<article class="item ${low?'low':''}"><div class="item-top"><div class="item-name">${escapeHtml(item.name)}<div class="category">${escapeHtml(item.category)}${item.barcode?' ・ '+escapeHtml(item.barcode):''}</div></div><div class="stock"><strong>${qty(item.currentStock)} ${escapeHtml(item.unit)}</strong><small>最低 ${qty(item.reorderLevel)} ${escapeHtml(item.unit)}</small></div></div><div class="prices"><span>販売 ${yen(item.salePriceYen)}</span><span>仕入 ${yen(item.costPriceYen)}</span></div><div class="actions">${item.saleEnabled?`<button class="btn" data-key="${escapeHtml(item.syncKey)}" data-type="sale">販売</button>`:''}<button class="btn light" data-key="${escapeHtml(item.syncKey)}" data-type="purchase">入荷</button><button class="btn light" data-key="${escapeHtml(item.syncKey)}" data-type="internal_use">館内使用</button><button class="btn outline" data-key="${escapeHtml(item.syncKey)}" data-type="more">その他</button></div></article>`}).join('')}
    function openMovement(key,type){const item=state.items.find(value=>value.syncKey===key);if(!item)return;state.selected=item;el('movementTitle').textContent=item.name;el('movementStock').textContent='現在庫：'+qty(item.currentStock)+' '+item.unit;el('type').value=type==='more'?'waste':type;el('quantity').value='1';el('note').value='';applyType();el('movementError').classList.add('hidden');el('movement').classList.remove('hidden')}
    function applyType(){const item=state.selected;const type=el('type').value;el('quantityLabel').textContent=type==='adjustment'?'調整後の実在庫':'数量';el('price').value=type==='sale'?(item?.salePriceYen??''):type==='purchase'?(item?.costPriceYen??''):''}
    async function saveMovement(){const item=state.selected;const quantity=Number(el('quantity').value);if(!item||!Number.isFinite(quantity)||quantity<0){el('movementError').textContent='数量を確認してください。';el('movementError').classList.remove('hidden');return}const button=el('saveMovement');button.disabled=true;try{const priceText=el('price').value.trim();const result=await api('/api/v1/inventory/movements',{method:'POST',body:JSON.stringify({itemIdentifier:item.syncKey,transactionUuid:uuid(),type:el('type').value,quantity,unitPriceYen:priceText===''?null:Number(priceText),note:el('note').value.trim()||null,deviceId:navigator.userAgent.includes('CrOS')?'chromebook':'mobile',occurredAt:new Date().toISOString()})});el('movement').classList.add('hidden');toast(result.itemName+' ・ 在庫 '+qty(result.stockAfter));await loadItems()}catch(error){el('movementError').textContent=error.message;el('movementError').classList.remove('hidden')}finally{button.disabled=false}}

    let scanStream=null,scanFrame=0,pendingBarcode='';
    const barcodeFormats=['ean_13','ean_8','upc_a','upc_e','code_128','code_39','qr_code'];
    function scanMessage(message,error=false){el('scanStatus').textContent=error?'':message;el('scanError').textContent=error?message:'';el('scanError').classList.toggle('hidden',!error)}
    async function openScanner(){el('scanner').classList.remove('hidden');el('scanCode').value='';scanMessage('バーコード番号の入力もできます。');setTimeout(()=>el('scanCode').focus(),80);if(globalThis.isSecureContext&&navigator.mediaDevices?.getUserMedia&&'BarcodeDetector' in globalThis){try{scanStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});el('scanVideo').srcObject=scanStream;el('scanVideo').classList.remove('hidden');await el('scanVideo').play();scanMessage('カメラをバーコードに向けてください。');scanVideoLoop()}catch(_){scanMessage('撮影ボタン、番号入力、USBリーダーを利用できます。')}}}
    function closeScanner(){cancelAnimationFrame(scanFrame);scanFrame=0;if(scanStream){scanStream.getTracks().forEach(track=>track.stop());scanStream=null}el('scanVideo').srcObject=null;el('scanVideo').classList.add('hidden');el('scanner').classList.add('hidden')}
    async function scanVideoLoop(){if(!scanStream||el('scanner').classList.contains('hidden'))return;try{const detector=new BarcodeDetector({formats:barcodeFormats});const codes=await detector.detect(el('scanVideo'));if(codes.length){await acceptBarcode(codes[0].rawValue);return}}catch(_){}scanFrame=requestAnimationFrame(scanVideoLoop)}
    async function acceptBarcode(raw){const code=String(raw||'').trim();if(!code)return;closeScanner();const item=state.items.find(value=>String(value.barcode||'')===code||String(value.sku||'')===code);if(item){toast('読み取り：'+item.name);openMovement(item.syncKey,item.saleEnabled?'sale':'purchase');return}pendingBarcode=code;el('unknownBarcode').textContent='読み取った番号：'+code+'\n新規商品の登録、または既存商品への紐付けができます。';el('assignItem').innerHTML=state.items.map(item=>`<option value="${escapeHtml(item.syncKey)}">${escapeHtml(item.name)}（在庫 ${qty(item.currentStock)} ${escapeHtml(item.unit)}）</option>`).join('');el('saveAssign').disabled=!state.items.length;el('assignError').classList.add('hidden');el('assignBarcode').classList.remove('hidden')}
    async function saveBarcodeAssignment(){const button=el('saveAssign');button.disabled=true;try{const result=await api('/api/v1/inventory/items/barcode',{method:'POST',body:JSON.stringify({itemIdentifier:el('assignItem').value,barcode:pendingBarcode})});el('assignBarcode').classList.add('hidden');await loadItems();toast(result.item.name+'にバーコードを登録しました');openMovement(result.item.syncKey,result.item.saleEnabled?'sale':'purchase')}catch(error){el('assignError').textContent=error.message;el('assignError').classList.remove('hidden')}finally{button.disabled=false}}
    function openNewItem(){el('assignBarcode').classList.add('hidden');el('newItemBarcode').textContent='読み取った番号：'+pendingBarcode;for(const id of ['newName','newCost','newSale','newSupplier'])el(id).value='';el('newCategory').value='食品';el('newUnit').value='個';el('newStock').value='0';el('newReorder').value='0';el('newItemError').classList.add('hidden');el('newItem').classList.remove('hidden');setTimeout(()=>el('newName').focus(),60)}
    async function saveNewItem(){const name=el('newName').value.trim(),category=el('newCategory').value.trim(),unit=el('newUnit').value.trim(),currentStock=readNumber(el('newStock').value,{empty:0}),reorderLevel=readNumber(el('newReorder').value,{empty:0}),cost=readNumber(el('newCost').value),sale=readNumber(el('newSale').value);if(!name){el('newItemError').textContent='商品名を入力してください。';el('newItemError').classList.remove('hidden');return}if(!category){el('newItemError').textContent='分類を入力してください。';el('newItemError').classList.remove('hidden');return}if(!unit){el('newItemError').textContent='単位を入力してください。';el('newItemError').classList.remove('hidden');return}if(!Number.isFinite(currentStock)||currentStock<0){el('newItemError').textContent='初期在庫は0以上の数字で入力してください。';el('newItemError').classList.remove('hidden');return}if(!Number.isFinite(reorderLevel)||reorderLevel<0){el('newItemError').textContent='最低在庫は0以上の数字で入力してください。';el('newItemError').classList.remove('hidden');return}if(Number.isNaN(cost)||Number.isNaN(sale)||cost!=null&&cost<0||sale!=null&&sale<0){el('newItemError').textContent='仕入単価と販売価格は0以上の数字で入力してください。';el('newItemError').classList.remove('hidden');return}const button=el('saveNewItem');button.disabled=true;try{const result=await api('/api/v1/inventory/items',{method:'POST',body:JSON.stringify({barcode:pendingBarcode,name,category,unit,currentStock,reorderLevel,costPriceYen:cost,salePriceYen:sale,supplier:el('newSupplier').value.trim()||null,saleEnabled:sale!=null})});el('newItem').classList.add('hidden');await loadItems();toast(result.item.name+'を登録しました');openMovement(result.item.syncKey,result.item.saleEnabled?'sale':'purchase')}catch(error){el('newItemError').textContent=error.message;el('newItemError').classList.remove('hidden')}finally{button.disabled=false}}
    async function decodePhoto(file){if(!file)return;scanMessage('画像を読み取っています…');try{const bitmap=await createImageBitmap(file);let code='';if('BarcodeDetector' in globalThis){try{const detector=new BarcodeDetector({formats:barcodeFormats});const found=await detector.detect(bitmap);code=found[0]?.rawValue||''}catch(_){}}if(!code)code=decodeRetailBarcode(bitmap);bitmap.close?.();if(!code){scanMessage('読み取れませんでした。バーコードを大きく、正面から撮影してください。',true);return}await acceptBarcode(code)}catch(_){scanMessage('画像を読み込めませんでした。',true)}finally{el('scanPhoto').value=''}}

    const L=['0001101','0011001','0010011','0111101','0100011','0110001','0101111','0111011','0110111','0001011'];
    const G=['0100111','0110011','0011011','0100001','0011101','0111001','0000101','0010001','0001001','0010111'];
    const R=['1110010','1100110','1101100','1000010','1011100','1001110','1010000','1000100','1001000','1110100'];
    const PARITY=['LLLLLL','LLGLGG','LLGGLG','LLGGGL','LGLLGG','LGGLLG','LGGGLL','LGLGLG','LGLGGL','LGGLGL'];
    function decodeRetailBarcode(bitmap){const max=1600,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),w=Math.max(1,Math.round(bitmap.width*scale)),h=Math.max(1,Math.round(bitmap.height*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(bitmap,0,0,w,h);const data=context.getImageData(0,0,w,h).data;for(const vertical of [false,true]){const across=vertical?h:w,cross=vertical?w:h;for(const ratio of [.35,.42,.5,.58,.65]){const center=Math.floor(cross*ratio),gray=[];for(let i=0;i<across;i++){let total=0,count=0;for(let d=-2;d<=2;d++){const c=Math.max(0,Math.min(cross-1,center+d)),x=vertical?c:i,y=vertical?i:c,index=(y*w+x)*4;total+=(data[index]*299+data[index+1]*587+data[index+2]*114)/1000;count++}gray.push(total/count)}const sorted=[...gray].sort((a,b)=>a-b),low=sorted[Math.floor(sorted.length*.12)],high=sorted[Math.floor(sorted.length*.82)];for(const mix of [.38,.46,.54,.62]){const threshold=low+(high-low)*mix,bits=gray.map(value=>value<threshold?1:0),decoded=decodeRuns(bits);if(decoded)return decoded}}}return ''}
    function decodeRuns(bits){const runs=[];let value=bits[0],start=0;for(let i=1;i<=bits.length;i++){if(i===bits.length||bits[i]!==value){runs.push({value,start,width:i-start});if(i<bits.length){value=bits[i];start=i}}}for(let r=0;r+2<runs.length;r++){const a=runs[r],b=runs[r+1],c=runs[r+2];if(a.value!==1||b.value!==0||c.value!==1)continue;const module=(a.width+b.width+c.width)/3;if(module<1||Math.max(a.width,b.width,c.width)>module*1.9||Math.min(a.width,b.width,c.width)<module*.45)continue;for(const length of [95,67])for(const factor of [.9,.94,.97,1,1.03,1.06,1.1])for(const shift of [-.35,0,.35]){const width=module*factor,origin=a.start+shift*width,sampled=[];for(let n=0;n<length;n++)sampled.push(bits[Math.max(0,Math.min(bits.length-1,Math.round(origin+(n+.5)*width)))]?'1':'0');const code=length===95?decodeEan13(sampled.join('')):decodeEan8(sampled.join(''));if(code)return code}}return ''}
    function digit(patterns,value){const index=patterns.indexOf(value);return index<0?null:String(index)}
    function validCheck(code){const digits=[...code].map(Number),check=digits.pop();let sum=0;if(code.length===13){digits.forEach((n,i)=>sum+=n*(i%2===0?1:3))}else{digits.forEach((n,i)=>sum+=n*(i%2===0?3:1))}return (10-sum%10)%10===check}
    function decodeEan13(bits){if(!bits.startsWith('101')||bits.slice(45,50)!=='01010'||!bits.endsWith('101'))return '';let left='',parity='';for(let i=0;i<6;i++){const value=bits.slice(3+i*7,10+i*7),l=digit(L,value),g=digit(G,value);if(l!==null){left+=l;parity+='L'}else if(g!==null){left+=g;parity+='G'}else return ''}const first=PARITY.indexOf(parity);if(first<0)return '';let right='';for(let i=0;i<6;i++){const value=digit(R,bits.slice(50+i*7,57+i*7));if(value===null)return '';right+=value}const code=String(first)+left+right;return validCheck(code)?code:''}
    function decodeEan8(bits){if(!bits.startsWith('101')||bits.slice(31,36)!=='01010'||!bits.endsWith('101'))return '';let code='';for(let i=0;i<4;i++){const value=digit(L,bits.slice(3+i*7,10+i*7));if(value===null)return '';code+=value}for(let i=0;i<4;i++){const value=digit(R,bits.slice(36+i*7,43+i*7));if(value===null)return '';code+=value}return validCheck(code)?code:''}

    el('connect').addEventListener('click',connect);el('token').addEventListener('keydown',event=>{if(event.key==='Enter')connect()});el('reload').addEventListener('click',loadItems);el('logout').addEventListener('click',()=>{localStorage.removeItem('jamoo_inventory_token');state.token='';el('token').value='';showLogin()});el('search').addEventListener('input',render);el('clear').addEventListener('click',()=>{el('search').value='';render()});el('scan').addEventListener('click',openScanner);el('cancelScan').addEventListener('click',closeScanner);el('scanPhoto').addEventListener('change',event=>decodePhoto(event.target.files?.[0]));el('useScanCode').addEventListener('click',()=>acceptBarcode(el('scanCode').value));el('scanCode').addEventListener('keydown',event=>{if(event.key==='Enter')acceptBarcode(el('scanCode').value)});el('cancelAssign').addEventListener('click',()=>el('assignBarcode').classList.add('hidden'));el('newFromBarcode').addEventListener('click',openNewItem);el('saveAssign').addEventListener('click',saveBarcodeAssignment);el('cancelNewItem').addEventListener('click',()=>el('newItem').classList.add('hidden'));el('saveNewItem').addEventListener('click',saveNewItem);el('content').addEventListener('click',event=>{const button=event.target.closest('[data-key]');if(button)openMovement(button.dataset.key,button.dataset.type)});el('type').addEventListener('change',applyType);el('cancelMovement').addEventListener('click',()=>el('movement').classList.add('hidden'));el('saveMovement').addEventListener('click',saveMovement);
    if(state.token){loadItems()}else{showLogin()}
    setInterval(()=>loadItems(true),3000);
  </script>
</body>
</html>''';
